version: '3.8'

services:
  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - "15432:5432"  # Expose container port 5432 as port 15432 on the host
    environment:
      POSTGRES_DB: word-counter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf  # Mount custom postgresql.conf
    command: >
      postgres -c "config_file=/etc/postgresql/postgresql.conf"

  activemq:
    image: rmohr/activemq:latest
    restart: always
    ports:
      - "8161:8161"  # Web console
      - "61616:61616" # OpenWire
      - "61613:61613" # Stomp
      - "1883:1883"   # MQTT
      - "5672:5672"   # AMQP
    volumes:
      - activemq_data:/var/lib/activemq/data
  
  init-db:
    image: postgres:latest
    depends_on:
      - postgresql
    environment:
      PGPASSWORD: postgres
    command: >
      bash -c 'until pg_isready -h postgresql -p 5432 -q -U postgres; do sleep 1; done &&
      psql -h postgresql -U postgres -d word-counter -c "CREATE USER \"word-counter\" WITH PASSWORD '\''word-counter'\'';" &&
      psql -h postgresql -U postgres -d word-counter -c "GRANT ALL PRIVILEGES ON DATABASE \"word-counter\" TO \"word-counter\";"'
 
 
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "5050:80"  # Expose pgAdmin web interface on port 5050
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  activemq_data:
  pgadmin_data:

